foodstand/users/urls.py
from django.urls import path

from foodstand.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    # path('food_stands/', views.foodStands, name='food_stands'),
    # path('food_stands/<slug:category_slug>/', views.foodStands, name='food_stand_list_by_category'),
    # path('food_stand_detail/<int:id>/<slug:slug>/', views.foodStand_detail, name='food_stand_detail'),
    path("food_stand/", views.food_stand_list, name="food_stand_list"),
    path(
        "food_stand/<int:pk>/<slug:slug>/",
        views.food_stand_detail,
        name="food_stand_detail",
    ),
    path("food_stand/create/", views.food_stand_create, name="food_stand_create"),
    path(
        "food_stand/<int:pk>/<slug:slug>/update/",
        views.food_stand_update,
        name="food_stand_update",
    ),
    path(
        "food_stand/<int:pk>/<slug:slug>/update-location/",
        views.update_location,
        name="update_location",
    ),
    # path('food_stand/<int:pk>/images/', views.food_stand_images, name='food_stand_images'),
    # path('food_stand/delete/<int:pk>/images/', views.delete_image, name='delete_image'),
    path("category/create/", views.category_create, name="category_create"),
    path("category/<slug:slug>/", views.category_detail, name="category_detail"),
    path(
        "food_stand/<int:pk>/<slug:slug>/images/",
        views.food_stand_images,
        name="food_stand_images",
    ),
    # path('food_stand/<int:pk>/images/<int:image_pk>/set_first/', views.set_first_image, name='set_first_image'),
    # path('categories/<int:pk>/', views.category_detail, name='category_detail'),
]

foodstand/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

main/forms.py
from crispy_bootstrap5.bootstrap5 import FloatingField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, Field, Layout, Submit
from django import forms

from .models import Category, Image, foodStand


class foodStandForm(forms.ModelForm):
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    new_category_name = forms.CharField(label="New Category Name", required=False)
    images = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={"multiple": True}), required=False
    )

    class Meta:
        model = foodStand
        fields = [
            "name",
            "phone_number",
            "description",
            "adress",
            "city",
            "state",
            "zipcode",
            "latitude",
            "longitude",
            "website",
            "categories",
            "nv_business_id",
            "business_name",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit("submit", "Create"))
        self.helper.layout = Layout(
            Field("categories"),
            HTML(
                '<a href="{% url "main:category_create" %}?next={{ request.path }}" class="button-link ">'
                '<button type="button" class="btn btn-primary mb-3">Category Create</button></a>'
            ),
            FloatingField("name"),
            FloatingField("phone_number"),
            FloatingField("business_name"),
            FloatingField("nv_business_id", required=True),
            FloatingField("description"),
            FloatingField("adress"),
            FloatingField("city"),
            FloatingField("state"),
            FloatingField("zipcode"),
            FloatingField("latitude"),
            FloatingField("longitude"),
            FloatingField("website"),
            FloatingField("images"),
        )
        self.fields["nv_business_id"].label = "NV Business ID"
        self.fields["categories"].widget.attrs.update(
            {"class": "form-select", "size": 10}
        )


class ImageForm(forms.ModelForm):
    images = forms.ImageField(
        required=False, widget=forms.ClearableFileInput(attrs={"multiple": True})
    )
    set_primary = forms.BooleanField(required=False, label="Set as primary")

    class Meta:
        model = Image
        fields = ["images", "set_primary"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit("submit", "Upload"))
        self.helper.form_tag = False
        self.helper.layout = Layout(
            FloatingField("images"),
        )


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name", "image", "description"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit("submit", "Create"))


class LocationUpdateForm(forms.ModelForm):
    class Meta:
        model = foodStand
        fields = ["latitude", "longitude"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.add_input(Submit("submit", "Update"))
        self.helper.layout = Layout("latitude", "longitude")

foodstand/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

foodstand/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

main/views.py
# import qrcode
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import CategoryForm, ImageForm, LocationUpdateForm, foodStandForm
from .models import Category, Image, foodStand


def home(
    request,
):
    foodstands = foodStand.objects.all()

    context = {
        "foodstands": [],
        "google_maps_api_key": settings.GOOGLE_MAPS_API_KEY,
    }
    for foodstand in foodstands:
        primary_image = foodstand.images.filter(is_primary=True).first()
        context["foodstands"].append((foodstand, primary_image))
    return render(request, "main/home.html", context)


def about(request):
    context = {"breadcrumb": [("Home", "/"), ("About", request.path)]}
    return render(request, "main/about.html", context)


def contact(request):
    context = {"breadcrumb": [("Home", "/"), ("Contact", request.path)]}
    return render(request, "main/contact.html", context)


def food_stand_detail(request, pk, slug):
    foodstand = get_object_or_404(foodStand, pk=pk, slug=slug)
    primary_image = foodstand.images.filter(is_primary=True).first()

    context = {
        "foodstand": foodstand,
        "primary_image": primary_image,
        "google_maps_api_key": settings.GOOGLE_MAPS_API_KEY,
        "breadcrumb": [
            ("Home", "/"),
            ("Food Stand List", "/food_stand/"),
            (foodstand.name, request.path),
        ],
    }
    return render(request, "main/food_stand_detail.html", context)


@login_required
def food_stand_create(request):
    if request.method == "POST":
        form = foodStandForm(request.POST, request.FILES)
        if form.is_valid():
            foodstand = form.save(commit=False)
            foodstand.owner = request.user
            foodstand.save()
            form.save_m2m()
            for image in request.FILES.getlist("images"):
                img = Image.objects.create(image=image)
                foodstand.images.add(img)
            messages.success(request, "Food Stand created successfully.")
            return redirect(
                "main:food_stand_detail", pk=foodstand.pk, slug=foodstand.slug
            )
    else:
        form = foodStandForm()
    return render(request, "main/food_stand_create.html", {"form": form})


@login_required
def category_create(request):
    if request.method == "POST":
        category = CategoryForm(request.POST, request.FILES)
        if category.is_valid():
            category = category.save()
            messages.success(request, "Category created successfully.")
            next_url = request.GET.get("next", reverse("main:home"))
            return redirect(next_url, slug=category.slug)
    else:
        category = CategoryForm()
    return render(request, "main/category_create.html", {"category": category})


@login_required
def food_stand_update(request, pk, slug):
    foodstand = get_object_or_404(foodStand, pk=pk, slug=slug)
    if foodstand.owner != request.user:
        return redirect("main:food_stand_detail", pk=pk, slug=slug)
    if request.method == "POST":
        form = foodStandForm(request.POST, instance=foodstand)
        if form.is_valid():
            foodstand = form.save()
            for image in request.FILES.getlist("images"):
                img = Image.objects.create(image=image)
                foodstand.images.add(img)
            messages.success(request, "Food Stand updated successfully.")
            return redirect(
                "main:food_stand_detail", pk=foodstand.pk, slug=foodstand.slug
            )
    else:
        form = foodStandForm(instance=foodstand)
    return render(
        request, "main/food_stand_update.html", {"form": form, "foodstand": foodstand}
    )


@login_required
def food_stand_images(request, pk, slug):
    foodstand = get_object_or_404(foodStand, pk=pk, slug=slug)
    images = foodstand.images.all()
    if foodstand.owner != request.user:
        return redirect("main:food_stand_detail", pk=pk, slug=slug)
    if request.method == "POST":
        form = ImageForm(request.POST, request.FILES)
        if "set_primary" in request.POST:
            primary_image_id = request.POST.get("id")
            for image in images:
                if str(image.id) == primary_image_id:
                    image.is_primary = True
                else:
                    image.is_primary = False
                image.save()
            messages.success(request, "Primary image set successfully.")
        elif "delete_image" in request.POST:
            image_id = request.POST.get("id")
            image = get_object_or_404(Image, id=image_id)
            image.delete()
            messages.success(request, "Image deleted successfully.")
        else:
            if form.is_valid():
                for image in request.FILES.getlist("images"):
                    img = Image.objects.create(image=image)
                    foodstand.images.add(img)

                messages.success(request, "Images uploaded successfully.")
            return redirect("main:food_stand_images", pk=pk, slug=slug)
    else:
        form = ImageForm()
    context = {
        "foodstand": foodstand,
        "images": images,
        "form": form,
    }
    return render(request, "main/food_stand_images.html", context)


def category_detail(request, slug):
    category = get_object_or_404(Category, slug=slug)
    foodstands = foodStand.objects.filter(categories=category)
    context = {
        "category": category,
        "foodstands": foodstands,
        "breadcrumb": [("Home", "/"), ("Category List", request.path)],
    }
    return render(request, "main/category_detail.html", context)


def food_stand_list(request):
    categories = Category.objects.all()
    selected_category = request.GET.get("category")
    if selected_category:
        foodstands = foodStand.objects.filter(categories__slug=selected_category)
        category = get_object_or_404(Category, slug=selected_category)
    else:
        foodstands = foodStand.objects.all()
        category = None

    breadcheck = []
    if not category:
        breadcheck = "All"
    else:
        breadcheck = category

    context = {
        "categories": categories,
        "foodstands": [],
        "category": category,
        "breadcrumb": [("Home", "/"), (breadcheck, request.path)],
    }

    for foodstand in foodstands:
        primary_image = foodstand.images.filter(is_primary=True).first()
        context["foodstands"].append((foodstand, primary_image))

    return render(request, "main/food_stand_list.html", context)


@login_required
def update_location(request, pk, slug):
    food_stand = foodStand.objects.get(pk=pk, slug=slug)
    if request.method == "POST":
        form = LocationUpdateForm(request.POST, instance=food_stand)
        if form.is_valid():
            form.save()
            return redirect("main:food_stand_detail", pk=pk, slug=slug)
    else:
        initial_data = {}
        latitude = request.GET.get("latitude")
        longitude = request.GET.get("longitude")
        if latitude and longitude:
            initial_data["latitude"] = latitude
            initial_data["longitude"] = longitude
        form = LocationUpdateForm(instance=food_stand, initial=initial_data)

    context = {
        "form": form,
    }
    return render(request, "main/update_location.html", context)


# def location_qr_code_view(request, id):
#     # Get the foodStand object based on the ID
#     food_stand = foodStand.objects.get(id=id)

#     # Construct the URL for the update_location view
#     url = reverse('main:update_location', args=[id])

#     # Generate the QR code image
#     qr = qrcode.QRCode(version=1, box_size=10, border=4)
#     qr.add_data(request.build_absolute_uri(url))
#     qr.make(fit=True)
#     img = qr.make_image(fill_color="black", back_color="white")

#     # Return the QR code image as an HTTP response
#     response = HttpResponse(content_type="image/png")
#     img.save(response, "PNG")
#     return response

foodstand/templates/main/about.html
{% extends "main/base.html" %}
{% block title %}
  About Us
{% endblock title %}
{% block content %}
{% load static i18n %}
    <main class="flex-shrink-0 mt-n3">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            {% for name, url in breadcrumb %}
                <li class="breadcrumb-item {% if forloop.last %}active{% endif %}">
                    {% if not forloop.last %}
                        <a href="{{ url }}">{{ name }}</a>
                    {% else %}
                        {{ name }}
                    {% endif %}
                </li>
            {% endfor %}
        </ol>
    </nav>
        <div class="container">
            <h1 class="mt-5">About Us HI OK</h1>
            <p class="lead">This is the about page for our website.</p>
            <p>
                Use <a href="#">the sticky footer with a fixed navbar</a> if need be, too.
            </p>
        </div>
    </main>
{% endblock content %}

foodstand/templates/main/category_card.html
<div class="text-center">
  <h2>Categories</h2>
</div>
<div class="row row-cols-1 row-cols-md-4 g-4">
  {% for category in categories %}
    <div class="card">
      <img src="{{ category.image.url }}"
           class="card-img-top"
           alt="{{ category.name }}"/>
      <div class="card-body">
        <h5 class="card-title">{{ category.name }}</h5>
        <p class="card-text">{{ category.description }}</p>
        <a href="{{ category.get_absolute_url }}" class="btn btn-primary">View Category</a
          >
        </div>
      </div>
    {% endfor %}
  </div>

foodstand/templates/main/category_create.html
{% extends "main/base.html" %}
{% load static i18n %}
{% block title %}
  {% if category %}
    {{ category.name }}
  {% else %}
  Create Category
  {% endif %}
{% endblock title %}

{% load crispy_forms_tags %}

{% block content %}
<main class="flex-shrink-0 mt-n3">
    <div class="container">
<div class="card mb-5">
    <div class="row g-0">
        <div>
            <div class="card-body">
                <h1>Create Category</h1>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% crispy category %}
                </form>
            </div>
        </div>
    </div>
</div>
</div>
</main>
{% endblock content %}

foodstand/templates/main/category_detail.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% load static i18n %}
{% block title %}
    {{ category.name }}
{% endblock title %}
{% block content %}
    <main class="flex-shrink-0 mt-n3">
        <div class="container">
            <div class="card mb-5">
                <div class="row g-0">
                    <div>
                        <h1>Category {{ category.name }}</h1>
                        {% if category.image %}<img src="{{ category.image.url }}" alt="{{ category.name }}"class="img-fluid"/>{% endif %}
                        <p>{{ category.description }} </p>
                        <div class="row">
                        <h3>Food Stands in {{ category.name }} Category</h3>
                        </div>
                    <div class="row">
                            {% for foodstand in foodstands %}
                                <div class="col-md-3 mb-3">
                                    <div class="card">
                                        {% if foodstand.images.all %}
                                            <img src="{{ foodstand.images.first.image.url }}"
                                                 alt="{{ foodstand.name }}"
                                                 class="card-img-top"/>
                                        {% endif %}
                                        <div class="card-body">
                                            <h5 class="card-title">{{ foodstand.name }}</h5>
                                            <p class="card-text">{{ foodstand.description }}</p>
                                            <a href="{% url 'main:food_stand_detail' pk=foodstand.pk slug=foodstand.slug %}"
                                               class="btn btn-primary">View</a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

foodstand/templates/main/food_stand_detail.html
{% extends "main/base.html" %}
{% block title %}
  {{ foodstand.name }}
{% endblock title %}
{% block content %}
{% load static i18n %}
  <script>
    var imageUrl = "{% static 'images/logo/restaurant.png' %}";
  </script>
<script>
  var foodStand =
          {
              name: "{{ foodstand.name }}",
              id: "{{ foodstand.id }}",
              slug: "{{ foodstand.slug }}",
              description: "{{ foodstand.description }}",
              address: "{{ foodstand.address }}",
              latitude: {{ foodstand.latitude }},
              longitude: {{ foodstand.longitude }},
              {% if primary_image %}
              image: "{{ primary_image.image.url }}",
              {% else %}
              image: "{{ foodstand.images.first.image.url }}",
              {% endif %}
          };
          console.log(foodStand)
</script>
  <main class="flex-shrink-0 mt-n3">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
          {% for name, url in breadcrumb %}
              <li class="breadcrumb-item {% if forloop.last %}active{% endif %}">
                  {% if not forloop.last %}
                      <a href="{{ url }}">{{ name }}</a>
                  {% else %}
                      {{ name }}
                  {% endif %}
              </li>
          {% endfor %}
      </ol>
  </nav>
    <div class="container mt-n3" >
      <div class="row">
        <div class="col-md-6" >
          {% if foodstand.images.all %}
            <div id="carouselExampleIndicators" class="carousel slide">
              <div class="carousel-indicators">
                {% for image in foodstand.images.all %}
                {% if forloop.first %}
                <button type="button"
                        data-bs-target="#carouselExampleIndicators"
                        data-bs-slide-to="{{ forloop.counter0 }}"
                        class="active"
                        aria-current="true">
                </button>
                {% else %}
                <button type="button"
                        data-bs-target="#carouselExampleIndicators"
                        data-bs-slide-to="{{ forloop.counter0 }}"></button>
                {% endif %}
                {% endfor %}

              </div>
              <div class="carousel-inner">
                {% for image in foodstand.images.all %}
                  <div class="carousel-item{% if forloop.first %} active{% endif %}">
                    <img src="{{ image.image.url }}"
                         class="d-block w-100"
                         alt="{{ foodstand.name }}"/>
                  </div>
                {% endfor %}
              </div>
              <button class="carousel-control-prev"
                      type="button"
                      data-bs-target="#carouselExampleIndicators"
                      data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next"
                      type="button"
                      data-bs-target="#carouselExampleIndicators"
                      data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
          {% endif %}
        </div>
        <div class="col-md-6">
          <div class="row">
          <h1>{{ foodstand.name }}</h1>
          <p>{{ foodstand.description }}</p>
        </div>
          <div class="row">
          <p>
            Categories:
            {% for category in foodstand.categories.all %}
              <a href="{% url 'main:category_detail' slug=category.slug %}">{{ category.name }}</a>
              {% if not forloop.last %},{% endif %}
            {% endfor %}
          </p>
        </div>
          <div class="row">
          {% if foodstand.owner == request.user %}
            <a href="{% url 'main:food_stand_update' pk=foodstand.pk slug=foodstand.slug %}"
               class="btn m-2 btn-primary">Edit My Stand</a>
            <a href="{% url 'main:food_stand_images' pk=foodstand.pk slug=foodstand.slug %}"
               class="btn m-2 btn-primary">Edit Images</a>
            <a href="{% url 'main:category_create' %}" class="btn m-2 btn-primary">Create Category for Stand</a>
            <a href="{% url 'main:update_location' pk=foodstand.pk slug=foodstand.slug %}" class="btn m-2 btn-primary">Update My Stand Location</a>
          {% endif %}
        </div>
        </div>
      </div>
      <div class="row">
        <h2>map</h2>
        <div id="mapDetail"></div>
      </div>
    </div>
  </main>
  <script type="text/javascript" src="{% static 'js/mapDetail.js'%}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key={{google_maps_api_key}}&callback=initMap&v=weekly"
          defer></script>
{% endblock content %}

foodstand/templates/main/food_stand_image_upload.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% load static i18n %}

{% block title %}
    Create Product
{% endblock title %}

{% block content %}
<div class="card mb-5">
    <div class="row g-0">
        <div>
            <div class="card-body">
    <h1>Upload Image for {{ foodstand.name }}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% crispy form %}
    </form>
</div>
</div>
</div>
</div>

{% endblock content %}

foodstand/templates/main/navbar.html
{% load static i18n %}
{% get_current_language as LANGUAGE_CODE %}
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url "main:home" %}">
      <img src="{% static 'images/logo/truck_stand_logo.png' %}"
           alt="Bootstrap"
           width="50px"
           height="50px"
           class="rounded-img"/>
    </a>
    <a class="navbar-brand" href="{% url "main:home" %}">Elko Food Stands</a>
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="offcanvas"
            data-bs-target="#offcanvasNavbar"
            aria-controls="offcanvasNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end"
         tabindex="-1"
         id="offcanvasNavbar"
         aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Elko Food Stands</h5>
        <button type="button"
                class="btn-close"
                data-bs-dismiss="offcanvas"
                aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-center flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link" href="{% url "main:home" %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url "main:contact" %}">Contact US</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "main:about" %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "main:food_stand_list" %}">Food Stands</a>
          </li>
          {% comment %} {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Logout ({{ user.username }})</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:food_stand_create' %}">Register Food Stand</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
            </li>
          {% endif %} {% endcomment %}
          {% if request.user.is_authenticated %}
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="nav-link" href="{% url 'users:detail' request.user.username %}">{% translate "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:food_stand_create' %}">Register Food Stand</a>
                </li>
              {% else %}
                {% if ACCOUNT_ALLOW_REGISTRATION %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
              </li>
              {% endif %}
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
                </li>
              {% endif %}
        </ul>
        {% comment %} <form class="d-flex" role="search">
          <input class="form-control me-2"
                 type="search"
                 placeholder="Search"
                 aria-label="Search"/>
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form> {% endcomment %}
      </div>
    </div>
  </div>
</nav>